# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/patmol
pkgincludedir = $(includedir)/patmol
pkglibdir = $(libdir)/patmol
pkglibexecdir = $(libexecdir)/patmol
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = patmpi$(EXEEXT) patmol$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in depcomp INSTALL compile install-sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_prog_cc_mpi.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_patmol_OBJECTS = patmol-shell.$(OBJEXT) patmol-center.$(OBJEXT) \
	patmol-basis.$(OBJEXT) patmol-dpmints.$(OBJEXT) \
	patmol-erifs.$(OBJEXT) patmol-mdd.$(OBJEXT) \
	patmol-mdr.$(OBJEXT) patmol-momints.$(OBJEXT) \
	patmol-oneints.$(OBJEXT) patmol-twoints.$(OBJEXT) \
	patmol-util.$(OBJEXT) patmol-spack_math.$(OBJEXT) \
	patmol-rys.$(OBJEXT) patmol-scfaux.$(OBJEXT) \
	patmol-patmol.$(OBJEXT) patmol-rhfscf.$(OBJEXT) \
	patmol-uhfscf.$(OBJEXT)
patmol_OBJECTS = $(am_patmol_OBJECTS)
patmol_LDADD = $(LDADD)
patmol_LINK = $(CCLD) $(patmol_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
am_patmpi_OBJECTS = patmpi-shell.$(OBJEXT) patmpi-center.$(OBJEXT) \
	patmpi-basis.$(OBJEXT) patmpi-dpmints.$(OBJEXT) \
	patmpi-erifs.$(OBJEXT) patmpi-mdd.$(OBJEXT) \
	patmpi-mdr.$(OBJEXT) patmpi-momints.$(OBJEXT) \
	patmpi-oneints.$(OBJEXT) patmpi-twoints.$(OBJEXT) \
	patmpi-util.$(OBJEXT) patmpi-spack_math.$(OBJEXT) \
	patmpi-rys.$(OBJEXT) patmpi-scfaux.$(OBJEXT) \
	patmpi-patmpi.$(OBJEXT) patmpi-rhfscf_mpi.$(OBJEXT) \
	patmpi-uhfscf_mpi.$(OBJEXT)
patmpi_OBJECTS = $(am_patmpi_OBJECTS)
patmpi_LDADD = $(LDADD)
patmpi_LINK = $(CCLD) $(patmpi_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(patmol_SOURCES) $(patmpi_SOURCES)
DIST_SOURCES = $(patmol_SOURCES) $(patmpi_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/patrick/Patmol/missing aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/patrick/Patmol/missing autoconf
AUTOHEADER = ${SHELL} /home/patrick/Patmol/missing autoheader
AUTOMAKE = ${SHELL} /home/patrick/Patmol/missing automake-1.14
AWK = gawk
CC = mpicc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = mpicc -E
CPPFLAGS = 
CXX = mpic++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lm 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/patrick/Patmol/missing makeinfo
MKDIR_P = /bin/mkdir -p
MPICC = 
OBJEXT = o
PACKAGE = patmol
PACKAGE_BUGREPORT = patjnichols@gmail.com
PACKAGE_NAME = PATMOL
PACKAGE_STRING = PATMOL 2.8
PACKAGE_TARNAME = patmol
PACKAGE_URL = 
PACKAGE_VERSION = 2.8
PATH_SEPARATOR = :
POW_LIB = 
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 2.8
abs_builddir = /home/patrick/Patmol
abs_srcdir = /home/patrick/Patmol
abs_top_builddir = /home/patrick/Patmol
abs_top_srcdir = /home/patrick/Patmol
ac_ct_CC = mpicc
ac_ct_CXX = mpic++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/patrick/Patmol/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
patmpi_SOURCES = shell.c center.c basis.c dpmints.c erifs.c mdd.c mdr.c momints.c oneints.c twoints.c util.c spack_math.c \
rys.c scfaux.c patmpi.c rhfscf_mpi.c uhfscf_mpi.c 

patmpi_CFLAGS = -DUSE_MPI -O3 -funroll-all-loops -ffast-math -mtune=core2
patmol_SOURCES = shell.c center.c basis.c dpmints.c erifs.c mdd.c mdr.c  momints.c oneints.c twoints.c util.c spack_math.c \
rys.c scfaux.c patmol.c rhfscf.c uhfscf.c 

patmol_CFLAGS = -O3 -funroll-all-loops -ffast-math -mtune=core2
BUILT_SOURCES = basis.c center.c dpmints.c erifs.c mdd.c mdr.c momints.c oneints.c patmol.c patmpi.c \
rhfscf.c rhfscf_mpi.c rys.c scfaux.c shell.c spack_math.c twoints.c uhfscf.c uhfscf_mpi.c util.c

all: $(BUILT_SOURCES) config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

patmol$(EXEEXT): $(patmol_OBJECTS) $(patmol_DEPENDENCIES) $(EXTRA_patmol_DEPENDENCIES) 
	@rm -f patmol$(EXEEXT)
	$(AM_V_CCLD)$(patmol_LINK) $(patmol_OBJECTS) $(patmol_LDADD) $(LIBS)

patmpi$(EXEEXT): $(patmpi_OBJECTS) $(patmpi_DEPENDENCIES) $(EXTRA_patmpi_DEPENDENCIES) 
	@rm -f patmpi$(EXEEXT)
	$(AM_V_CCLD)$(patmpi_LINK) $(patmpi_OBJECTS) $(patmpi_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/patmol-basis.Po
include ./$(DEPDIR)/patmol-center.Po
include ./$(DEPDIR)/patmol-dpmints.Po
include ./$(DEPDIR)/patmol-erifs.Po
include ./$(DEPDIR)/patmol-mdd.Po
include ./$(DEPDIR)/patmol-mdr.Po
include ./$(DEPDIR)/patmol-momints.Po
include ./$(DEPDIR)/patmol-oneints.Po
include ./$(DEPDIR)/patmol-patmol.Po
include ./$(DEPDIR)/patmol-rhfscf.Po
include ./$(DEPDIR)/patmol-rys.Po
include ./$(DEPDIR)/patmol-scfaux.Po
include ./$(DEPDIR)/patmol-shell.Po
include ./$(DEPDIR)/patmol-spack_math.Po
include ./$(DEPDIR)/patmol-twoints.Po
include ./$(DEPDIR)/patmol-uhfscf.Po
include ./$(DEPDIR)/patmol-util.Po
include ./$(DEPDIR)/patmpi-basis.Po
include ./$(DEPDIR)/patmpi-center.Po
include ./$(DEPDIR)/patmpi-dpmints.Po
include ./$(DEPDIR)/patmpi-erifs.Po
include ./$(DEPDIR)/patmpi-mdd.Po
include ./$(DEPDIR)/patmpi-mdr.Po
include ./$(DEPDIR)/patmpi-momints.Po
include ./$(DEPDIR)/patmpi-oneints.Po
include ./$(DEPDIR)/patmpi-patmpi.Po
include ./$(DEPDIR)/patmpi-rhfscf_mpi.Po
include ./$(DEPDIR)/patmpi-rys.Po
include ./$(DEPDIR)/patmpi-scfaux.Po
include ./$(DEPDIR)/patmpi-shell.Po
include ./$(DEPDIR)/patmpi-spack_math.Po
include ./$(DEPDIR)/patmpi-twoints.Po
include ./$(DEPDIR)/patmpi-uhfscf_mpi.Po
include ./$(DEPDIR)/patmpi-util.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

patmol-shell.o: shell.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-shell.o -MD -MP -MF $(DEPDIR)/patmol-shell.Tpo -c -o patmol-shell.o `test -f 'shell.c' || echo '$(srcdir)/'`shell.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-shell.Tpo $(DEPDIR)/patmol-shell.Po
#	$(AM_V_CC)source='shell.c' object='patmol-shell.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-shell.o `test -f 'shell.c' || echo '$(srcdir)/'`shell.c

patmol-shell.obj: shell.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-shell.obj -MD -MP -MF $(DEPDIR)/patmol-shell.Tpo -c -o patmol-shell.obj `if test -f 'shell.c'; then $(CYGPATH_W) 'shell.c'; else $(CYGPATH_W) '$(srcdir)/shell.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-shell.Tpo $(DEPDIR)/patmol-shell.Po
#	$(AM_V_CC)source='shell.c' object='patmol-shell.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-shell.obj `if test -f 'shell.c'; then $(CYGPATH_W) 'shell.c'; else $(CYGPATH_W) '$(srcdir)/shell.c'; fi`

patmol-center.o: center.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-center.o -MD -MP -MF $(DEPDIR)/patmol-center.Tpo -c -o patmol-center.o `test -f 'center.c' || echo '$(srcdir)/'`center.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-center.Tpo $(DEPDIR)/patmol-center.Po
#	$(AM_V_CC)source='center.c' object='patmol-center.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-center.o `test -f 'center.c' || echo '$(srcdir)/'`center.c

patmol-center.obj: center.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-center.obj -MD -MP -MF $(DEPDIR)/patmol-center.Tpo -c -o patmol-center.obj `if test -f 'center.c'; then $(CYGPATH_W) 'center.c'; else $(CYGPATH_W) '$(srcdir)/center.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-center.Tpo $(DEPDIR)/patmol-center.Po
#	$(AM_V_CC)source='center.c' object='patmol-center.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-center.obj `if test -f 'center.c'; then $(CYGPATH_W) 'center.c'; else $(CYGPATH_W) '$(srcdir)/center.c'; fi`

patmol-basis.o: basis.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-basis.o -MD -MP -MF $(DEPDIR)/patmol-basis.Tpo -c -o patmol-basis.o `test -f 'basis.c' || echo '$(srcdir)/'`basis.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-basis.Tpo $(DEPDIR)/patmol-basis.Po
#	$(AM_V_CC)source='basis.c' object='patmol-basis.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-basis.o `test -f 'basis.c' || echo '$(srcdir)/'`basis.c

patmol-basis.obj: basis.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-basis.obj -MD -MP -MF $(DEPDIR)/patmol-basis.Tpo -c -o patmol-basis.obj `if test -f 'basis.c'; then $(CYGPATH_W) 'basis.c'; else $(CYGPATH_W) '$(srcdir)/basis.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-basis.Tpo $(DEPDIR)/patmol-basis.Po
#	$(AM_V_CC)source='basis.c' object='patmol-basis.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-basis.obj `if test -f 'basis.c'; then $(CYGPATH_W) 'basis.c'; else $(CYGPATH_W) '$(srcdir)/basis.c'; fi`

patmol-dpmints.o: dpmints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-dpmints.o -MD -MP -MF $(DEPDIR)/patmol-dpmints.Tpo -c -o patmol-dpmints.o `test -f 'dpmints.c' || echo '$(srcdir)/'`dpmints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-dpmints.Tpo $(DEPDIR)/patmol-dpmints.Po
#	$(AM_V_CC)source='dpmints.c' object='patmol-dpmints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-dpmints.o `test -f 'dpmints.c' || echo '$(srcdir)/'`dpmints.c

patmol-dpmints.obj: dpmints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-dpmints.obj -MD -MP -MF $(DEPDIR)/patmol-dpmints.Tpo -c -o patmol-dpmints.obj `if test -f 'dpmints.c'; then $(CYGPATH_W) 'dpmints.c'; else $(CYGPATH_W) '$(srcdir)/dpmints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-dpmints.Tpo $(DEPDIR)/patmol-dpmints.Po
#	$(AM_V_CC)source='dpmints.c' object='patmol-dpmints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-dpmints.obj `if test -f 'dpmints.c'; then $(CYGPATH_W) 'dpmints.c'; else $(CYGPATH_W) '$(srcdir)/dpmints.c'; fi`

patmol-erifs.o: erifs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-erifs.o -MD -MP -MF $(DEPDIR)/patmol-erifs.Tpo -c -o patmol-erifs.o `test -f 'erifs.c' || echo '$(srcdir)/'`erifs.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-erifs.Tpo $(DEPDIR)/patmol-erifs.Po
#	$(AM_V_CC)source='erifs.c' object='patmol-erifs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-erifs.o `test -f 'erifs.c' || echo '$(srcdir)/'`erifs.c

patmol-erifs.obj: erifs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-erifs.obj -MD -MP -MF $(DEPDIR)/patmol-erifs.Tpo -c -o patmol-erifs.obj `if test -f 'erifs.c'; then $(CYGPATH_W) 'erifs.c'; else $(CYGPATH_W) '$(srcdir)/erifs.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-erifs.Tpo $(DEPDIR)/patmol-erifs.Po
#	$(AM_V_CC)source='erifs.c' object='patmol-erifs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-erifs.obj `if test -f 'erifs.c'; then $(CYGPATH_W) 'erifs.c'; else $(CYGPATH_W) '$(srcdir)/erifs.c'; fi`

patmol-mdd.o: mdd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-mdd.o -MD -MP -MF $(DEPDIR)/patmol-mdd.Tpo -c -o patmol-mdd.o `test -f 'mdd.c' || echo '$(srcdir)/'`mdd.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-mdd.Tpo $(DEPDIR)/patmol-mdd.Po
#	$(AM_V_CC)source='mdd.c' object='patmol-mdd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-mdd.o `test -f 'mdd.c' || echo '$(srcdir)/'`mdd.c

patmol-mdd.obj: mdd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-mdd.obj -MD -MP -MF $(DEPDIR)/patmol-mdd.Tpo -c -o patmol-mdd.obj `if test -f 'mdd.c'; then $(CYGPATH_W) 'mdd.c'; else $(CYGPATH_W) '$(srcdir)/mdd.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-mdd.Tpo $(DEPDIR)/patmol-mdd.Po
#	$(AM_V_CC)source='mdd.c' object='patmol-mdd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-mdd.obj `if test -f 'mdd.c'; then $(CYGPATH_W) 'mdd.c'; else $(CYGPATH_W) '$(srcdir)/mdd.c'; fi`

patmol-mdr.o: mdr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-mdr.o -MD -MP -MF $(DEPDIR)/patmol-mdr.Tpo -c -o patmol-mdr.o `test -f 'mdr.c' || echo '$(srcdir)/'`mdr.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-mdr.Tpo $(DEPDIR)/patmol-mdr.Po
#	$(AM_V_CC)source='mdr.c' object='patmol-mdr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-mdr.o `test -f 'mdr.c' || echo '$(srcdir)/'`mdr.c

patmol-mdr.obj: mdr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-mdr.obj -MD -MP -MF $(DEPDIR)/patmol-mdr.Tpo -c -o patmol-mdr.obj `if test -f 'mdr.c'; then $(CYGPATH_W) 'mdr.c'; else $(CYGPATH_W) '$(srcdir)/mdr.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-mdr.Tpo $(DEPDIR)/patmol-mdr.Po
#	$(AM_V_CC)source='mdr.c' object='patmol-mdr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-mdr.obj `if test -f 'mdr.c'; then $(CYGPATH_W) 'mdr.c'; else $(CYGPATH_W) '$(srcdir)/mdr.c'; fi`

patmol-momints.o: momints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-momints.o -MD -MP -MF $(DEPDIR)/patmol-momints.Tpo -c -o patmol-momints.o `test -f 'momints.c' || echo '$(srcdir)/'`momints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-momints.Tpo $(DEPDIR)/patmol-momints.Po
#	$(AM_V_CC)source='momints.c' object='patmol-momints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-momints.o `test -f 'momints.c' || echo '$(srcdir)/'`momints.c

patmol-momints.obj: momints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-momints.obj -MD -MP -MF $(DEPDIR)/patmol-momints.Tpo -c -o patmol-momints.obj `if test -f 'momints.c'; then $(CYGPATH_W) 'momints.c'; else $(CYGPATH_W) '$(srcdir)/momints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-momints.Tpo $(DEPDIR)/patmol-momints.Po
#	$(AM_V_CC)source='momints.c' object='patmol-momints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-momints.obj `if test -f 'momints.c'; then $(CYGPATH_W) 'momints.c'; else $(CYGPATH_W) '$(srcdir)/momints.c'; fi`

patmol-oneints.o: oneints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-oneints.o -MD -MP -MF $(DEPDIR)/patmol-oneints.Tpo -c -o patmol-oneints.o `test -f 'oneints.c' || echo '$(srcdir)/'`oneints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-oneints.Tpo $(DEPDIR)/patmol-oneints.Po
#	$(AM_V_CC)source='oneints.c' object='patmol-oneints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-oneints.o `test -f 'oneints.c' || echo '$(srcdir)/'`oneints.c

patmol-oneints.obj: oneints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-oneints.obj -MD -MP -MF $(DEPDIR)/patmol-oneints.Tpo -c -o patmol-oneints.obj `if test -f 'oneints.c'; then $(CYGPATH_W) 'oneints.c'; else $(CYGPATH_W) '$(srcdir)/oneints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-oneints.Tpo $(DEPDIR)/patmol-oneints.Po
#	$(AM_V_CC)source='oneints.c' object='patmol-oneints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-oneints.obj `if test -f 'oneints.c'; then $(CYGPATH_W) 'oneints.c'; else $(CYGPATH_W) '$(srcdir)/oneints.c'; fi`

patmol-twoints.o: twoints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-twoints.o -MD -MP -MF $(DEPDIR)/patmol-twoints.Tpo -c -o patmol-twoints.o `test -f 'twoints.c' || echo '$(srcdir)/'`twoints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-twoints.Tpo $(DEPDIR)/patmol-twoints.Po
#	$(AM_V_CC)source='twoints.c' object='patmol-twoints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-twoints.o `test -f 'twoints.c' || echo '$(srcdir)/'`twoints.c

patmol-twoints.obj: twoints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-twoints.obj -MD -MP -MF $(DEPDIR)/patmol-twoints.Tpo -c -o patmol-twoints.obj `if test -f 'twoints.c'; then $(CYGPATH_W) 'twoints.c'; else $(CYGPATH_W) '$(srcdir)/twoints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-twoints.Tpo $(DEPDIR)/patmol-twoints.Po
#	$(AM_V_CC)source='twoints.c' object='patmol-twoints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-twoints.obj `if test -f 'twoints.c'; then $(CYGPATH_W) 'twoints.c'; else $(CYGPATH_W) '$(srcdir)/twoints.c'; fi`

patmol-util.o: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-util.o -MD -MP -MF $(DEPDIR)/patmol-util.Tpo -c -o patmol-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-util.Tpo $(DEPDIR)/patmol-util.Po
#	$(AM_V_CC)source='util.c' object='patmol-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c

patmol-util.obj: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-util.obj -MD -MP -MF $(DEPDIR)/patmol-util.Tpo -c -o patmol-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-util.Tpo $(DEPDIR)/patmol-util.Po
#	$(AM_V_CC)source='util.c' object='patmol-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`

patmol-spack_math.o: spack_math.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-spack_math.o -MD -MP -MF $(DEPDIR)/patmol-spack_math.Tpo -c -o patmol-spack_math.o `test -f 'spack_math.c' || echo '$(srcdir)/'`spack_math.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-spack_math.Tpo $(DEPDIR)/patmol-spack_math.Po
#	$(AM_V_CC)source='spack_math.c' object='patmol-spack_math.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-spack_math.o `test -f 'spack_math.c' || echo '$(srcdir)/'`spack_math.c

patmol-spack_math.obj: spack_math.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-spack_math.obj -MD -MP -MF $(DEPDIR)/patmol-spack_math.Tpo -c -o patmol-spack_math.obj `if test -f 'spack_math.c'; then $(CYGPATH_W) 'spack_math.c'; else $(CYGPATH_W) '$(srcdir)/spack_math.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-spack_math.Tpo $(DEPDIR)/patmol-spack_math.Po
#	$(AM_V_CC)source='spack_math.c' object='patmol-spack_math.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-spack_math.obj `if test -f 'spack_math.c'; then $(CYGPATH_W) 'spack_math.c'; else $(CYGPATH_W) '$(srcdir)/spack_math.c'; fi`

patmol-rys.o: rys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-rys.o -MD -MP -MF $(DEPDIR)/patmol-rys.Tpo -c -o patmol-rys.o `test -f 'rys.c' || echo '$(srcdir)/'`rys.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-rys.Tpo $(DEPDIR)/patmol-rys.Po
#	$(AM_V_CC)source='rys.c' object='patmol-rys.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-rys.o `test -f 'rys.c' || echo '$(srcdir)/'`rys.c

patmol-rys.obj: rys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-rys.obj -MD -MP -MF $(DEPDIR)/patmol-rys.Tpo -c -o patmol-rys.obj `if test -f 'rys.c'; then $(CYGPATH_W) 'rys.c'; else $(CYGPATH_W) '$(srcdir)/rys.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-rys.Tpo $(DEPDIR)/patmol-rys.Po
#	$(AM_V_CC)source='rys.c' object='patmol-rys.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-rys.obj `if test -f 'rys.c'; then $(CYGPATH_W) 'rys.c'; else $(CYGPATH_W) '$(srcdir)/rys.c'; fi`

patmol-scfaux.o: scfaux.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-scfaux.o -MD -MP -MF $(DEPDIR)/patmol-scfaux.Tpo -c -o patmol-scfaux.o `test -f 'scfaux.c' || echo '$(srcdir)/'`scfaux.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-scfaux.Tpo $(DEPDIR)/patmol-scfaux.Po
#	$(AM_V_CC)source='scfaux.c' object='patmol-scfaux.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-scfaux.o `test -f 'scfaux.c' || echo '$(srcdir)/'`scfaux.c

patmol-scfaux.obj: scfaux.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-scfaux.obj -MD -MP -MF $(DEPDIR)/patmol-scfaux.Tpo -c -o patmol-scfaux.obj `if test -f 'scfaux.c'; then $(CYGPATH_W) 'scfaux.c'; else $(CYGPATH_W) '$(srcdir)/scfaux.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-scfaux.Tpo $(DEPDIR)/patmol-scfaux.Po
#	$(AM_V_CC)source='scfaux.c' object='patmol-scfaux.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-scfaux.obj `if test -f 'scfaux.c'; then $(CYGPATH_W) 'scfaux.c'; else $(CYGPATH_W) '$(srcdir)/scfaux.c'; fi`

patmol-patmol.o: patmol.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-patmol.o -MD -MP -MF $(DEPDIR)/patmol-patmol.Tpo -c -o patmol-patmol.o `test -f 'patmol.c' || echo '$(srcdir)/'`patmol.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-patmol.Tpo $(DEPDIR)/patmol-patmol.Po
#	$(AM_V_CC)source='patmol.c' object='patmol-patmol.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-patmol.o `test -f 'patmol.c' || echo '$(srcdir)/'`patmol.c

patmol-patmol.obj: patmol.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-patmol.obj -MD -MP -MF $(DEPDIR)/patmol-patmol.Tpo -c -o patmol-patmol.obj `if test -f 'patmol.c'; then $(CYGPATH_W) 'patmol.c'; else $(CYGPATH_W) '$(srcdir)/patmol.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-patmol.Tpo $(DEPDIR)/patmol-patmol.Po
#	$(AM_V_CC)source='patmol.c' object='patmol-patmol.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-patmol.obj `if test -f 'patmol.c'; then $(CYGPATH_W) 'patmol.c'; else $(CYGPATH_W) '$(srcdir)/patmol.c'; fi`

patmol-rhfscf.o: rhfscf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-rhfscf.o -MD -MP -MF $(DEPDIR)/patmol-rhfscf.Tpo -c -o patmol-rhfscf.o `test -f 'rhfscf.c' || echo '$(srcdir)/'`rhfscf.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-rhfscf.Tpo $(DEPDIR)/patmol-rhfscf.Po
#	$(AM_V_CC)source='rhfscf.c' object='patmol-rhfscf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-rhfscf.o `test -f 'rhfscf.c' || echo '$(srcdir)/'`rhfscf.c

patmol-rhfscf.obj: rhfscf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-rhfscf.obj -MD -MP -MF $(DEPDIR)/patmol-rhfscf.Tpo -c -o patmol-rhfscf.obj `if test -f 'rhfscf.c'; then $(CYGPATH_W) 'rhfscf.c'; else $(CYGPATH_W) '$(srcdir)/rhfscf.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-rhfscf.Tpo $(DEPDIR)/patmol-rhfscf.Po
#	$(AM_V_CC)source='rhfscf.c' object='patmol-rhfscf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-rhfscf.obj `if test -f 'rhfscf.c'; then $(CYGPATH_W) 'rhfscf.c'; else $(CYGPATH_W) '$(srcdir)/rhfscf.c'; fi`

patmol-uhfscf.o: uhfscf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-uhfscf.o -MD -MP -MF $(DEPDIR)/patmol-uhfscf.Tpo -c -o patmol-uhfscf.o `test -f 'uhfscf.c' || echo '$(srcdir)/'`uhfscf.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-uhfscf.Tpo $(DEPDIR)/patmol-uhfscf.Po
#	$(AM_V_CC)source='uhfscf.c' object='patmol-uhfscf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-uhfscf.o `test -f 'uhfscf.c' || echo '$(srcdir)/'`uhfscf.c

patmol-uhfscf.obj: uhfscf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -MT patmol-uhfscf.obj -MD -MP -MF $(DEPDIR)/patmol-uhfscf.Tpo -c -o patmol-uhfscf.obj `if test -f 'uhfscf.c'; then $(CYGPATH_W) 'uhfscf.c'; else $(CYGPATH_W) '$(srcdir)/uhfscf.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmol-uhfscf.Tpo $(DEPDIR)/patmol-uhfscf.Po
#	$(AM_V_CC)source='uhfscf.c' object='patmol-uhfscf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmol_CFLAGS) $(CFLAGS) -c -o patmol-uhfscf.obj `if test -f 'uhfscf.c'; then $(CYGPATH_W) 'uhfscf.c'; else $(CYGPATH_W) '$(srcdir)/uhfscf.c'; fi`

patmpi-shell.o: shell.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-shell.o -MD -MP -MF $(DEPDIR)/patmpi-shell.Tpo -c -o patmpi-shell.o `test -f 'shell.c' || echo '$(srcdir)/'`shell.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-shell.Tpo $(DEPDIR)/patmpi-shell.Po
#	$(AM_V_CC)source='shell.c' object='patmpi-shell.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-shell.o `test -f 'shell.c' || echo '$(srcdir)/'`shell.c

patmpi-shell.obj: shell.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-shell.obj -MD -MP -MF $(DEPDIR)/patmpi-shell.Tpo -c -o patmpi-shell.obj `if test -f 'shell.c'; then $(CYGPATH_W) 'shell.c'; else $(CYGPATH_W) '$(srcdir)/shell.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-shell.Tpo $(DEPDIR)/patmpi-shell.Po
#	$(AM_V_CC)source='shell.c' object='patmpi-shell.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-shell.obj `if test -f 'shell.c'; then $(CYGPATH_W) 'shell.c'; else $(CYGPATH_W) '$(srcdir)/shell.c'; fi`

patmpi-center.o: center.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-center.o -MD -MP -MF $(DEPDIR)/patmpi-center.Tpo -c -o patmpi-center.o `test -f 'center.c' || echo '$(srcdir)/'`center.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-center.Tpo $(DEPDIR)/patmpi-center.Po
#	$(AM_V_CC)source='center.c' object='patmpi-center.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-center.o `test -f 'center.c' || echo '$(srcdir)/'`center.c

patmpi-center.obj: center.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-center.obj -MD -MP -MF $(DEPDIR)/patmpi-center.Tpo -c -o patmpi-center.obj `if test -f 'center.c'; then $(CYGPATH_W) 'center.c'; else $(CYGPATH_W) '$(srcdir)/center.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-center.Tpo $(DEPDIR)/patmpi-center.Po
#	$(AM_V_CC)source='center.c' object='patmpi-center.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-center.obj `if test -f 'center.c'; then $(CYGPATH_W) 'center.c'; else $(CYGPATH_W) '$(srcdir)/center.c'; fi`

patmpi-basis.o: basis.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-basis.o -MD -MP -MF $(DEPDIR)/patmpi-basis.Tpo -c -o patmpi-basis.o `test -f 'basis.c' || echo '$(srcdir)/'`basis.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-basis.Tpo $(DEPDIR)/patmpi-basis.Po
#	$(AM_V_CC)source='basis.c' object='patmpi-basis.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-basis.o `test -f 'basis.c' || echo '$(srcdir)/'`basis.c

patmpi-basis.obj: basis.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-basis.obj -MD -MP -MF $(DEPDIR)/patmpi-basis.Tpo -c -o patmpi-basis.obj `if test -f 'basis.c'; then $(CYGPATH_W) 'basis.c'; else $(CYGPATH_W) '$(srcdir)/basis.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-basis.Tpo $(DEPDIR)/patmpi-basis.Po
#	$(AM_V_CC)source='basis.c' object='patmpi-basis.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-basis.obj `if test -f 'basis.c'; then $(CYGPATH_W) 'basis.c'; else $(CYGPATH_W) '$(srcdir)/basis.c'; fi`

patmpi-dpmints.o: dpmints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-dpmints.o -MD -MP -MF $(DEPDIR)/patmpi-dpmints.Tpo -c -o patmpi-dpmints.o `test -f 'dpmints.c' || echo '$(srcdir)/'`dpmints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-dpmints.Tpo $(DEPDIR)/patmpi-dpmints.Po
#	$(AM_V_CC)source='dpmints.c' object='patmpi-dpmints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-dpmints.o `test -f 'dpmints.c' || echo '$(srcdir)/'`dpmints.c

patmpi-dpmints.obj: dpmints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-dpmints.obj -MD -MP -MF $(DEPDIR)/patmpi-dpmints.Tpo -c -o patmpi-dpmints.obj `if test -f 'dpmints.c'; then $(CYGPATH_W) 'dpmints.c'; else $(CYGPATH_W) '$(srcdir)/dpmints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-dpmints.Tpo $(DEPDIR)/patmpi-dpmints.Po
#	$(AM_V_CC)source='dpmints.c' object='patmpi-dpmints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-dpmints.obj `if test -f 'dpmints.c'; then $(CYGPATH_W) 'dpmints.c'; else $(CYGPATH_W) '$(srcdir)/dpmints.c'; fi`

patmpi-erifs.o: erifs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-erifs.o -MD -MP -MF $(DEPDIR)/patmpi-erifs.Tpo -c -o patmpi-erifs.o `test -f 'erifs.c' || echo '$(srcdir)/'`erifs.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-erifs.Tpo $(DEPDIR)/patmpi-erifs.Po
#	$(AM_V_CC)source='erifs.c' object='patmpi-erifs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-erifs.o `test -f 'erifs.c' || echo '$(srcdir)/'`erifs.c

patmpi-erifs.obj: erifs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-erifs.obj -MD -MP -MF $(DEPDIR)/patmpi-erifs.Tpo -c -o patmpi-erifs.obj `if test -f 'erifs.c'; then $(CYGPATH_W) 'erifs.c'; else $(CYGPATH_W) '$(srcdir)/erifs.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-erifs.Tpo $(DEPDIR)/patmpi-erifs.Po
#	$(AM_V_CC)source='erifs.c' object='patmpi-erifs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-erifs.obj `if test -f 'erifs.c'; then $(CYGPATH_W) 'erifs.c'; else $(CYGPATH_W) '$(srcdir)/erifs.c'; fi`

patmpi-mdd.o: mdd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-mdd.o -MD -MP -MF $(DEPDIR)/patmpi-mdd.Tpo -c -o patmpi-mdd.o `test -f 'mdd.c' || echo '$(srcdir)/'`mdd.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-mdd.Tpo $(DEPDIR)/patmpi-mdd.Po
#	$(AM_V_CC)source='mdd.c' object='patmpi-mdd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-mdd.o `test -f 'mdd.c' || echo '$(srcdir)/'`mdd.c

patmpi-mdd.obj: mdd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-mdd.obj -MD -MP -MF $(DEPDIR)/patmpi-mdd.Tpo -c -o patmpi-mdd.obj `if test -f 'mdd.c'; then $(CYGPATH_W) 'mdd.c'; else $(CYGPATH_W) '$(srcdir)/mdd.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-mdd.Tpo $(DEPDIR)/patmpi-mdd.Po
#	$(AM_V_CC)source='mdd.c' object='patmpi-mdd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-mdd.obj `if test -f 'mdd.c'; then $(CYGPATH_W) 'mdd.c'; else $(CYGPATH_W) '$(srcdir)/mdd.c'; fi`

patmpi-mdr.o: mdr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-mdr.o -MD -MP -MF $(DEPDIR)/patmpi-mdr.Tpo -c -o patmpi-mdr.o `test -f 'mdr.c' || echo '$(srcdir)/'`mdr.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-mdr.Tpo $(DEPDIR)/patmpi-mdr.Po
#	$(AM_V_CC)source='mdr.c' object='patmpi-mdr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-mdr.o `test -f 'mdr.c' || echo '$(srcdir)/'`mdr.c

patmpi-mdr.obj: mdr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-mdr.obj -MD -MP -MF $(DEPDIR)/patmpi-mdr.Tpo -c -o patmpi-mdr.obj `if test -f 'mdr.c'; then $(CYGPATH_W) 'mdr.c'; else $(CYGPATH_W) '$(srcdir)/mdr.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-mdr.Tpo $(DEPDIR)/patmpi-mdr.Po
#	$(AM_V_CC)source='mdr.c' object='patmpi-mdr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-mdr.obj `if test -f 'mdr.c'; then $(CYGPATH_W) 'mdr.c'; else $(CYGPATH_W) '$(srcdir)/mdr.c'; fi`

patmpi-momints.o: momints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-momints.o -MD -MP -MF $(DEPDIR)/patmpi-momints.Tpo -c -o patmpi-momints.o `test -f 'momints.c' || echo '$(srcdir)/'`momints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-momints.Tpo $(DEPDIR)/patmpi-momints.Po
#	$(AM_V_CC)source='momints.c' object='patmpi-momints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-momints.o `test -f 'momints.c' || echo '$(srcdir)/'`momints.c

patmpi-momints.obj: momints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-momints.obj -MD -MP -MF $(DEPDIR)/patmpi-momints.Tpo -c -o patmpi-momints.obj `if test -f 'momints.c'; then $(CYGPATH_W) 'momints.c'; else $(CYGPATH_W) '$(srcdir)/momints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-momints.Tpo $(DEPDIR)/patmpi-momints.Po
#	$(AM_V_CC)source='momints.c' object='patmpi-momints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-momints.obj `if test -f 'momints.c'; then $(CYGPATH_W) 'momints.c'; else $(CYGPATH_W) '$(srcdir)/momints.c'; fi`

patmpi-oneints.o: oneints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-oneints.o -MD -MP -MF $(DEPDIR)/patmpi-oneints.Tpo -c -o patmpi-oneints.o `test -f 'oneints.c' || echo '$(srcdir)/'`oneints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-oneints.Tpo $(DEPDIR)/patmpi-oneints.Po
#	$(AM_V_CC)source='oneints.c' object='patmpi-oneints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-oneints.o `test -f 'oneints.c' || echo '$(srcdir)/'`oneints.c

patmpi-oneints.obj: oneints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-oneints.obj -MD -MP -MF $(DEPDIR)/patmpi-oneints.Tpo -c -o patmpi-oneints.obj `if test -f 'oneints.c'; then $(CYGPATH_W) 'oneints.c'; else $(CYGPATH_W) '$(srcdir)/oneints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-oneints.Tpo $(DEPDIR)/patmpi-oneints.Po
#	$(AM_V_CC)source='oneints.c' object='patmpi-oneints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-oneints.obj `if test -f 'oneints.c'; then $(CYGPATH_W) 'oneints.c'; else $(CYGPATH_W) '$(srcdir)/oneints.c'; fi`

patmpi-twoints.o: twoints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-twoints.o -MD -MP -MF $(DEPDIR)/patmpi-twoints.Tpo -c -o patmpi-twoints.o `test -f 'twoints.c' || echo '$(srcdir)/'`twoints.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-twoints.Tpo $(DEPDIR)/patmpi-twoints.Po
#	$(AM_V_CC)source='twoints.c' object='patmpi-twoints.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-twoints.o `test -f 'twoints.c' || echo '$(srcdir)/'`twoints.c

patmpi-twoints.obj: twoints.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-twoints.obj -MD -MP -MF $(DEPDIR)/patmpi-twoints.Tpo -c -o patmpi-twoints.obj `if test -f 'twoints.c'; then $(CYGPATH_W) 'twoints.c'; else $(CYGPATH_W) '$(srcdir)/twoints.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-twoints.Tpo $(DEPDIR)/patmpi-twoints.Po
#	$(AM_V_CC)source='twoints.c' object='patmpi-twoints.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-twoints.obj `if test -f 'twoints.c'; then $(CYGPATH_W) 'twoints.c'; else $(CYGPATH_W) '$(srcdir)/twoints.c'; fi`

patmpi-util.o: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-util.o -MD -MP -MF $(DEPDIR)/patmpi-util.Tpo -c -o patmpi-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-util.Tpo $(DEPDIR)/patmpi-util.Po
#	$(AM_V_CC)source='util.c' object='patmpi-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c

patmpi-util.obj: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-util.obj -MD -MP -MF $(DEPDIR)/patmpi-util.Tpo -c -o patmpi-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-util.Tpo $(DEPDIR)/patmpi-util.Po
#	$(AM_V_CC)source='util.c' object='patmpi-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`

patmpi-spack_math.o: spack_math.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-spack_math.o -MD -MP -MF $(DEPDIR)/patmpi-spack_math.Tpo -c -o patmpi-spack_math.o `test -f 'spack_math.c' || echo '$(srcdir)/'`spack_math.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-spack_math.Tpo $(DEPDIR)/patmpi-spack_math.Po
#	$(AM_V_CC)source='spack_math.c' object='patmpi-spack_math.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-spack_math.o `test -f 'spack_math.c' || echo '$(srcdir)/'`spack_math.c

patmpi-spack_math.obj: spack_math.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-spack_math.obj -MD -MP -MF $(DEPDIR)/patmpi-spack_math.Tpo -c -o patmpi-spack_math.obj `if test -f 'spack_math.c'; then $(CYGPATH_W) 'spack_math.c'; else $(CYGPATH_W) '$(srcdir)/spack_math.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-spack_math.Tpo $(DEPDIR)/patmpi-spack_math.Po
#	$(AM_V_CC)source='spack_math.c' object='patmpi-spack_math.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-spack_math.obj `if test -f 'spack_math.c'; then $(CYGPATH_W) 'spack_math.c'; else $(CYGPATH_W) '$(srcdir)/spack_math.c'; fi`

patmpi-rys.o: rys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-rys.o -MD -MP -MF $(DEPDIR)/patmpi-rys.Tpo -c -o patmpi-rys.o `test -f 'rys.c' || echo '$(srcdir)/'`rys.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-rys.Tpo $(DEPDIR)/patmpi-rys.Po
#	$(AM_V_CC)source='rys.c' object='patmpi-rys.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-rys.o `test -f 'rys.c' || echo '$(srcdir)/'`rys.c

patmpi-rys.obj: rys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-rys.obj -MD -MP -MF $(DEPDIR)/patmpi-rys.Tpo -c -o patmpi-rys.obj `if test -f 'rys.c'; then $(CYGPATH_W) 'rys.c'; else $(CYGPATH_W) '$(srcdir)/rys.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-rys.Tpo $(DEPDIR)/patmpi-rys.Po
#	$(AM_V_CC)source='rys.c' object='patmpi-rys.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-rys.obj `if test -f 'rys.c'; then $(CYGPATH_W) 'rys.c'; else $(CYGPATH_W) '$(srcdir)/rys.c'; fi`

patmpi-scfaux.o: scfaux.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-scfaux.o -MD -MP -MF $(DEPDIR)/patmpi-scfaux.Tpo -c -o patmpi-scfaux.o `test -f 'scfaux.c' || echo '$(srcdir)/'`scfaux.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-scfaux.Tpo $(DEPDIR)/patmpi-scfaux.Po
#	$(AM_V_CC)source='scfaux.c' object='patmpi-scfaux.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-scfaux.o `test -f 'scfaux.c' || echo '$(srcdir)/'`scfaux.c

patmpi-scfaux.obj: scfaux.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-scfaux.obj -MD -MP -MF $(DEPDIR)/patmpi-scfaux.Tpo -c -o patmpi-scfaux.obj `if test -f 'scfaux.c'; then $(CYGPATH_W) 'scfaux.c'; else $(CYGPATH_W) '$(srcdir)/scfaux.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-scfaux.Tpo $(DEPDIR)/patmpi-scfaux.Po
#	$(AM_V_CC)source='scfaux.c' object='patmpi-scfaux.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-scfaux.obj `if test -f 'scfaux.c'; then $(CYGPATH_W) 'scfaux.c'; else $(CYGPATH_W) '$(srcdir)/scfaux.c'; fi`

patmpi-patmpi.o: patmpi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-patmpi.o -MD -MP -MF $(DEPDIR)/patmpi-patmpi.Tpo -c -o patmpi-patmpi.o `test -f 'patmpi.c' || echo '$(srcdir)/'`patmpi.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-patmpi.Tpo $(DEPDIR)/patmpi-patmpi.Po
#	$(AM_V_CC)source='patmpi.c' object='patmpi-patmpi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-patmpi.o `test -f 'patmpi.c' || echo '$(srcdir)/'`patmpi.c

patmpi-patmpi.obj: patmpi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-patmpi.obj -MD -MP -MF $(DEPDIR)/patmpi-patmpi.Tpo -c -o patmpi-patmpi.obj `if test -f 'patmpi.c'; then $(CYGPATH_W) 'patmpi.c'; else $(CYGPATH_W) '$(srcdir)/patmpi.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-patmpi.Tpo $(DEPDIR)/patmpi-patmpi.Po
#	$(AM_V_CC)source='patmpi.c' object='patmpi-patmpi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-patmpi.obj `if test -f 'patmpi.c'; then $(CYGPATH_W) 'patmpi.c'; else $(CYGPATH_W) '$(srcdir)/patmpi.c'; fi`

patmpi-rhfscf_mpi.o: rhfscf_mpi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-rhfscf_mpi.o -MD -MP -MF $(DEPDIR)/patmpi-rhfscf_mpi.Tpo -c -o patmpi-rhfscf_mpi.o `test -f 'rhfscf_mpi.c' || echo '$(srcdir)/'`rhfscf_mpi.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-rhfscf_mpi.Tpo $(DEPDIR)/patmpi-rhfscf_mpi.Po
#	$(AM_V_CC)source='rhfscf_mpi.c' object='patmpi-rhfscf_mpi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-rhfscf_mpi.o `test -f 'rhfscf_mpi.c' || echo '$(srcdir)/'`rhfscf_mpi.c

patmpi-rhfscf_mpi.obj: rhfscf_mpi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-rhfscf_mpi.obj -MD -MP -MF $(DEPDIR)/patmpi-rhfscf_mpi.Tpo -c -o patmpi-rhfscf_mpi.obj `if test -f 'rhfscf_mpi.c'; then $(CYGPATH_W) 'rhfscf_mpi.c'; else $(CYGPATH_W) '$(srcdir)/rhfscf_mpi.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-rhfscf_mpi.Tpo $(DEPDIR)/patmpi-rhfscf_mpi.Po
#	$(AM_V_CC)source='rhfscf_mpi.c' object='patmpi-rhfscf_mpi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-rhfscf_mpi.obj `if test -f 'rhfscf_mpi.c'; then $(CYGPATH_W) 'rhfscf_mpi.c'; else $(CYGPATH_W) '$(srcdir)/rhfscf_mpi.c'; fi`

patmpi-uhfscf_mpi.o: uhfscf_mpi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-uhfscf_mpi.o -MD -MP -MF $(DEPDIR)/patmpi-uhfscf_mpi.Tpo -c -o patmpi-uhfscf_mpi.o `test -f 'uhfscf_mpi.c' || echo '$(srcdir)/'`uhfscf_mpi.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-uhfscf_mpi.Tpo $(DEPDIR)/patmpi-uhfscf_mpi.Po
#	$(AM_V_CC)source='uhfscf_mpi.c' object='patmpi-uhfscf_mpi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-uhfscf_mpi.o `test -f 'uhfscf_mpi.c' || echo '$(srcdir)/'`uhfscf_mpi.c

patmpi-uhfscf_mpi.obj: uhfscf_mpi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -MT patmpi-uhfscf_mpi.obj -MD -MP -MF $(DEPDIR)/patmpi-uhfscf_mpi.Tpo -c -o patmpi-uhfscf_mpi.obj `if test -f 'uhfscf_mpi.c'; then $(CYGPATH_W) 'uhfscf_mpi.c'; else $(CYGPATH_W) '$(srcdir)/uhfscf_mpi.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/patmpi-uhfscf_mpi.Tpo $(DEPDIR)/patmpi-uhfscf_mpi.Po
#	$(AM_V_CC)source='uhfscf_mpi.c' object='patmpi-uhfscf_mpi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(patmpi_CFLAGS) $(CFLAGS) -c -o patmpi-uhfscf_mpi.obj `if test -f 'uhfscf_mpi.c'; then $(CYGPATH_W) 'uhfscf_mpi.c'; else $(CYGPATH_W) '$(srcdir)/uhfscf_mpi.c'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all check install install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
